### ISSUE TITLE
OpenWire Plugin automatically reconnect to ActiveMQ after downtime

### ISSUE THREAD

**Issue by atarallo** [exabrial/graylog-plugin-openwire#3]
I've been using version **1.1.0** of the plugin without incidents for a few weeks.

We noticed after downtime of the queue, or any interruption in communication between plugin and ActiveMQ, the INPUT must be stoped and re started in order to continue ingesting messages from the queue. 

Does the plugin support any kind of automatic reconnection? I'm investigating how to monitor the Queue and restart the INPUT from Graylog API. But I think that automatic reconnection will be interesteng.

**Comment by exabrial** [comment]
Yes absolutely, as a matter of fact, this is done by the ActiveMQ client library itself. We restart things fearlessly in production all day because it's so reliable :)

The example URL will automatically reconnect: `failover:(ssl://activemq-1.example.com:61616)`. For more advanced options, see the ActiveMQ failover transport documentation: https://activemq.apache.org/failover-transport-reference

**Comment by atarallo** [comment]
Thanks for your feedback, I´ll be testing this on my servers.
